# Generated by Django 6.0.2 on 2026-02-05 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['day_of_week', 'time']},
        ),
        migrations.AddField(
            model_name='schedule',
            name='building',
            field=models.CharField(blank=True, max_length=50, verbose_name='Корпус'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='classroom_floor',
            field=models.IntegerField(blank=True, null=True, verbose_name='Этаж'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='classroom_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Номер аудитории'),
        ),
    ]
