# Generated by Django 6.0.2 on 2026-02-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_alter_schedule_options_schedule_building_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='half',
            field=models.IntegerField(choices=[(1, '1 половина'), (2, '2 половина')], default=1, verbose_name='Половина пары'),
        ),
    ]
