# Generated by Django 6.0.2 on 2026-02-05 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_schedule_half'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='half',
        ),
        migrations.AddField(
            model_name='group',
            name='curator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curated_groups', to='schedule.teacher'),
        ),
        migrations.AddField(
            model_name='group',
            name='specialty',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='schedule',
            name='duration',
            field=models.CharField(choices=[('half1', '1 половина'), ('half2', '2 половина'), ('full', 'Полная пара')], default='full', max_length=10),
        ),
    ]
